name: DepthAI GUI CI/CD

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux2014_x86_64:2021-11-15-a808c18
      env:
        PLAT: manylinux2014_x86_64
    steps:
    - name: Get current tag
      id: tag
      uses: battila7/get-version-action@v2
   # Create GitHub release
    - uses: actions/checkout@v2
    - name: Create folder structure
      run: mkdir -p wheelhouse/audited/
    - name: Building source distribution
      run: |
        /opt/python/cp38-cp38/bin/python3.8 setup.py sdist --formats=gztar
        mv dist/* wheelhouse/audited/
    - name: Build wheels
      run: /opt/python/cp38-cp38/bin/python3.8 -m pip wheel . -w ./wheelhouse/ --verbose
    - name: Audit wheels
      run: for whl in wheelhouse/*.whl; do auditwheel repair "$whl" --plat $PLAT -w wheelhouse/audited/; done
    - name: Run deploy to PyPi
      run: bash ./ci/upload-pypi.sh
      env:
        PYPI_SERVER: ${{ secrets.PYPI_SERVER }}
        PYPI_USER: ${{ secrets.PYPI_USER }}
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
    - uses: actions/create-release@master
      id: createRelease
      name: Create ${{ steps.tag.outputs.version }} DepthAI GUI release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.version }}
        release_name: depthai-gui ${{ steps.tag.outputs.version }}
        draft: true
